### ISSUE TITLE
Expose playerVars

### ISSUE THREAD

**Issue by olivierlesnicki** [paramaggarwal/react-native-youtube#10]
Such as rel, controls, etc...
https://developers.google.com/youtube/player_parameters?hl=en

**Comment by paramaggarwal** [comment]
Yes, the internal version has it. I'll update the OSS version soon.

**Comment by olivierlesnicki** [comment]
Nice one :)

**Comment by paramaggarwal** [comment]
Fixed! Please try out `v0.2.0` from npm.
https://github.com/paramaggarwal/react-native-youtube/releases/tag/v0.2.0

**Comment by olivierlesnicki** [comment]
An example of how to use this? @paramaggarwal
