### ISSUE TITLE
Use of undeclared identifier 'RNYouTubeEventReady'

### ISSUE THREAD

**Issue by alejomendoza** [paramaggarwal/react-native-youtube#13]
![screen shot 2015-09-03 at 10 22 57 am](https://cloud.githubusercontent.com/assets/5351127/9662653/f6827350-5225-11e5-8ed7-f0902100f30a.png)

**Comment by paramaggarwal** [comment]
:( My latest changes broke this... In RN 0.10, this will just be `@"youtubeReady"` etc. right?

**Comment by paramaggarwal** [comment]
Fixed: https://github.com/paramaggarwal/react-native-youtube/commit/b3fa4626dd77884ef354f778bf6b07d86b00ee76
