### ISSUE TITLE
RCTViewManager.h file not found

### ISSUE THREAD

**Issue by tolu360** [paramaggarwal/react-native-youtube#2]
Hello,

On installing your library, I came up against this error - `RCTViewManager.h file not found` and my project is not able to build. Please what step of the installation process do you think I missed or what could be wrong? I am on v 0.8.0

Thanks.

**Comment by paramaggarwal** [comment]
Not completely sure. That file is in RN itself... Could you verify it is part of your project?

**Comment by tolu360** [comment]
Yes I can confirm the file is in `React.xcodeproj/React/Views`. Perhaps I would try to update your Example project to 0.8.0 and see if it works, just to be sure the library is not broken in the version.

**Comment by jevakallio** [comment]
Experiencing the same issue, on React Native 0.9.0-rc. The `RCTViewManager.h` header file exists and is successfully imported from a number of other third-party plugins.

I managed to solve the problem by setting the User Header Search Paths config for `RCTYouTube.xcodeproj` as suggested in a similar issue https://github.com/corymsmith/react-native-icons/issues/6.

![Screen shot](https://cloud.githubusercontent.com/assets/1203949/9042379/20a9f5fa-3a06-11e5-8f95-acc9faa5f2e1.png)

I don't understand XCode and the iOS build chain well enough to suggest how to solve this problem, but this workaround seems to do the job @tolu360 @paramaggarwal .

**Comment by tolu360** [comment]
Thanks for sharing that @jevakallio, would give it a try.

**Comment by paramaggarwal** [comment]
Published to npm as `v0.1.1`.

**Comment by piyush565** [comment]
/Users/../node_modules/react-native-material-kit/iOS/RCTMaterialKit/TickViewManager.m:9:9: 'React/RCTViewManager.h' file not found

can anybody help me with this.? build gets failed in this
