### ISSUE TITLE
Unable to resolve module ReactNativeViewAttributes error

### ISSUE THREAD

**Issue by alvinwoon** [paramaggarwal/react-native-youtube#36]
on latest RN - 0.14.1

**Comment by holmesal** [comment]
Looks like this was fixed in 0f7419afedd4e189e090f1e01e31f160803c18cd, but I don't think that fix was pushed to npm. Until that's fixed, pointing package.json at the master branch of this repo seems to work.

**Comment by paramaggarwal** [comment]
Sorry about that. Published `react-native-youtube@0.5.0` to npm.

**Comment by alvinwoon** [comment]
Thanks man. Appreciate it.
