### ISSUE TITLE
Video doesn't play after upgrading to React Native 0.14.2

### ISSUE THREAD

**Issue by BilalBudhani** [paramaggarwal/react-native-youtube#37]
After upgrading to `"react-native": "0.14.2"` this component stopped working. Now it just shows blank black screen and video doesn't play. Also, to mark it doesn't throw any error in runtime.

**Comment by sebglazebrook** [comment]
+1

**Comment by paramaggarwal** [comment]
Fixed in 98c56936b0cd197c2fe633ff02a5f4e94d6fc6df thanks to @jaygarcia and available in `react-native-youtube@0.6.0`.
