### ISSUE TITLE
Build fails with React Native 0.16

### ISSUE THREAD

**Issue by vanBrunneren** [paramaggarwal/react-native-youtube#38]
Hi 

I tried your plugin with RN 0.16. In most cases Xcode's build process failed silently as soon as I implemented this plugin as shown in the README. Furthermore I saw yo're using RCTSparseArray.h in the RCTYouTubeManager.m as I know this is replaced by NSDictionary in version 0.16. 

Are you planing to upgrade your project or should I look for another solution?

Thanks for an Answer and your plugin :smirk:

**Comment by alvinwoon** [comment]
+1

**Comment by vanBrunneren** [comment]
I just managed to play a youtube video with a WebView. Just did it like this:

```
<WebView
  url={"EMBEDED LINK FOR YOUTUBE VIDEO"} />
```

If you don't want to make something complicated and just want to playing a video in your app you're going great with my solution :smirk: 

cheers

**Comment by richarddewit** [comment]
@vanBrunneren You lose the ability to autoplay though :<

**Comment by vanBrunneren** [comment]
@richarddewit yes that's true, but not really needed in my case

there are several answers why this isn't possible out of the box.
maybe you want to have a look at: http://stackoverflow.com/questions/8141652/youtube-embedded-video-autoplay-feature-not-working-in-iphone

why do you want to autoplay youtube videos? Maybe (no not maybe, there is :smile: ) another solution for doing this. 
Do you tried to do that with JavaScript? There is a great API from youtube.
Are these your own videos? Maybe you can play them with the great react-native-video plugin?
Maybe you can give a goal on fixing this plugin?

Let me know if I can help you out :smirk: 
Cheers

**Comment by alvinwoon** [comment]
You can autoplay with url parameter but it would be nice to have a working,
native player as always :D

**Comment by richarddewit** [comment]
@alvinwoon - No that doesn't work on iOS sadly

**Comment by richarddewit** [comment]
@vanBrunneren - What I wanted is to display a placeholder image, then when clicked, replaces it with the player, which then starts playing, now requiring 2 clicks from the user.

I have tried using JavaScript, but that way I have to put an iframe in the `html` attribute of the WebView because it needs an `id` to be able to communicate with the API. That way the content is no longer 'filling' the webview (tried all the other attributes like `automaticallyAdjustContentInsets` and `scalesPageToFit ` to make it fill).

**Comment by linh81** [comment]
+1

**Comment by paramaggarwal** [comment]
Open for PRs! I have not dabbled with RN 0.16.0 yet...

**Comment by robtg4** [comment]
this really need to get fixed! too important of a component to just sit! :)

**Comment by paramaggarwal** [comment]
Fixed in 98c56936b0cd197c2fe633ff02a5f4e94d6fc6df thanks to @jaygarcia and available in `react-native-youtube@0.6.0`.
