### ISSUE TITLE
RCTYoutubeManager is returning nil for its methodQueue, which is not permitted.

### ISSUE THREAD

**Issue by jevakallio** [paramaggarwal/react-native-youtube#4]
Since React Native 0.7.0, I am seeing the error `RCTYoutubeManager is returning nil for its methodQueue, which is not permitted`:
![screen shot 2015-08-04 at 08 59 50](https://cloud.githubusercontent.com/assets/1203949/9056135/afa09fe8-3a88-11e5-892f-a8faf819f522.png)

The issue is basically the same as https://github.com/brentvatne/react-native-video/issues/69.

PR incoming.

**Comment by paramaggarwal** [comment]
Thanks! Published to npm as `v0.1.3`.
