### ISSUE TITLE
React Documentation

### ISSUE THREAD

**Issue by shaundon** [paramaggarwal/react-native-youtube#8]
Hi,

Great work on this plugin, it's brill! I'm about to attempt writing a similar React component (a wrapper for the [OpenTok iOS SDK](https://tokbox.com/developer/sdks/ios/) for video chat). I've been looking through your code as there are lots of similarities with what I'm trying to do, like async events, native UI needing to be exposed, and so on.

I was wondering, do you have any links to resources you used when developing this plugin? I've looked at the official React documentation for developing components that use native UI but it doesn't seem to address what I want to do.

Thanks!

**Comment by paramaggarwal** [comment]
Thanks @shaundon. This code is heavily built off @brentvatne's `react-native-video` component. https://github.com/brentvatne/react-native-video
