### ISSUE TITLE
Update to V.0.10

### ISSUE THREAD

**Issue by alejomendoza** [paramaggarwal/react-native-youtube#9]
I get this error when updating to the latest react-native V.0.10

'customDirectEventTypes must return an array, but RCTYouTubeManager returned __NSDictionaryI'

**Comment by paramaggarwal** [comment]
Ah yes, I had to change that too when I was trying out the new `0.10-rc`. You need to make it simply an array like this:

```objective-c
- (NSArray *)customDirectEventTypes
{
    return @[
             @"ready",
             @"changeState",
             @"changeQuality",
             @"error"
             ];
}
```

**Comment by alejomendoza** [comment]
Thank you! @paramaggarwal, that solved that issue. Also with the new version I think you would have to update how to require the modules. I get the errors Unable to resolve module StyleSheetPropType in the packager.
![packager](https://cloud.githubusercontent.com/assets/5351127/9376674/030a26aa-46d6-11e5-845e-4ef17b9cfec9.png)

**Comment by paramaggarwal** [comment]
Please try out `v0.2.0` from npm: https://github.com/paramaggarwal/react-native-youtube/releases/tag/v0.2.0 and let me know if you still face issue.

Regarding supporting RN 0.10.0 - not sure how to support it in a backward compatible way...

**Comment by alejomendoza** [comment]
hmm, I still face that issue with v0.2.0, I think it would be better for you to support react native's latest version

**Comment by alejomendoza** [comment]
https://github.com/alejomendoza/react-native-youtube/commit/f99204786cc529ea32a0e3f280b0fb232b7a30a0

**Comment by paramaggarwal** [comment]
Yes, let's make this change now that 0.10 is stable.
